### ISSUE TITLE
Compile error when using app:binding

### ISSUE THREAD

**Issue by Hanspagh** [fabioCollini/mv2m#4]
I am getting the following error, when I try to use the app:binding tag
I have imported compile 'com.github.fabioCollini:twowaydatabinding:0.1' like in the demo, any idea whats wrong

`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.`
`> java.lang.RuntimeException: Found data binding errors.`
`****/ data binding error ****msg:Cannot find the setter for attribute 'app:binding' with parameter type``java.lang.String.`
`file:\res\layout\activity_login.xml`
`loc:29:31 - 29:51`
`****\ data binding error ****
`

**Comment by fabioCollini** [comment]
Hi, which object are using in the app:binding attribute? You should use an ObservableString, it seems that you are using a normal String.

**Comment by Hanspagh** [comment]
That was the problem thanks :+1:
